//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityLeGang
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int Id { get; set; }
        public string Тип_агента { get; set; }
        public string Наименование_агента { get; set; }
        public string Номер_телефона { get; set; }
        public Nullable<double> Приоритет { get; set; }
        public Nullable<int> Скидка_агента { get; set; }
        public Nullable<double> Количество_продаж_за_год { get; set; }
        public string LogoAgent { get; set; }
    }
}
