//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCalculatZP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTasks
    {
        public int ID { get; set; }
        public Nullable<int> IdExecuterOld { get; set; }
        public Nullable<int> IdExecuterNew { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Task { get; set; }
    }
}
