//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCalculatZP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int ID { get; set; }
        public int ExecuterID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CreateDateTime { get; set; }
        public System.DateTime Deadline { get; set; }
        public int Difficulty { get; set; }
        public int Time { get; set; }
        public int StatusID { get; set; }
        public int WorkTypeID { get; set; }
        public string CompletedDateTime { get; set; }
        public byte IsDeleted { get; set; }
    
        public virtual Executers Executers { get; set; }
        public virtual Status Status { get; set; }
        public virtual WorkTypes WorkTypes { get; set; }
    }
}
