//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCalculatZP
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ExecutersDetails1
    {
        public string Middlename { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string NameGrade { get; set; }
        public Nullable<int> Запланированно { get; set; }
        public Nullable<int> Исполняется { get; set; }
        public Nullable<int> Завершено { get; set; }
        public Nullable<int> Отменено { get; set; }
        public string ManagerMiddlename { get; set; }
        public string ManagerName { get; set; }
        public string ManagerLastname { get; set; }
    }
}
